### ISSUE TITLE
测试跨项目的 commit 引用

### ISSUE THREAD

**Issue by bitorb** [gaixie/sandbox#1]
测试

**Comment by bitorb** [comment]
gaixie/jibu-core@d5462f2883321c82d898c8752b7e5eba4b7dc184

**Comment by bitorb** [comment]
gaixie/jibu-core@d5462f2883321c82d898c8752b7e5eba4b7dc184

**Comment by huozhicheng** [comment]
gaixie/jibu-core@d5462f2
